import {
  FabricFloor,
  FloorAnnotation,
  FloorGrid,
  PathGraph,
  RouteSequence,
  TileDefinition,
} from "@/lib/floor-plan/types";

const tileColor = {
  slate: "#0f172a",
  slateLight: "#1e293b",
  gray: "#475569",
  emerald: "#22c55e",
  cyan: "#0ea5e9",
  amber: "#fbbf24",
  fuchsia: "#a855f7",
  rose: "#fb7185",
  red: "#b91c1c",
  teal: "#14b8a6",
};

export const tileDefinitions: TileDefinition[] = [
  {
    id: 0,
    label: "Technician desk",
    description: "Start and end point for every field round trip.",
    fill: "#164e63",
    border: "#5eead4",
    textColor: "#ecfeff",
  },
  {
    id: 1,
    label: "GPU pod · in use",
    description: "Fully utilized racks pushing thermal envelope.",
    fill: tileColor.emerald,
    border: "#86efac",
    slurmDiagnostics: {
      allocation: "92% allocated · 410/448 GPUs",
      thermals: "Exhaust 32°C · liquid loop steady",
      notes: "Running H100 queues + active NVLink fabric",
    },
  },
  {
    id: 2,
    label: "Mixed workload",
    description: "Shared CPU/GPU sleds; allocation is fluid.",
    fill: tileColor.cyan,
    border: "#22d3ee",
    slurmDiagnostics: {
      allocation: "61% allocated · 180 GPU eq / 220 CPU cores",
      thermals: "Exhaust 27°C · intake 19°C",
      notes: "Slurm partition MIX-02: preemptible jobs allowed",
    },
  },
  {
    id: 3,
    label: "Idle / standby",
    description: "Capacity available for burst or maintenance.",
    fill: tileColor.gray,
    border: "#cbd5f5",
    slurmDiagnostics: {
      allocation: "5% reserved · 0 active jobs",
      thermals: "Idle 22°C · fans low power",
      notes: "Ready for provisioning or diagnostics",
    },
  },
  {
    id: 4,
    label: "Hot aisle",
    description: "High thermal zone between opposing racks.",
    fill: tileColor.red,
    border: "#fecaca",
  },
  {
    id: 5,
    label: "Cold aisle",
    description: "Conditioned intake path for chilled air.",
    fill: "#0a192f",
    border: "#38bdf8",
  },
  {
    id: 6,
    label: "Inventory cache",
    description: "Spare parts staging, optics, or gaskets.",
    fill: tileColor.amber,
    border: "#fde047",
    textColor: "#0f172a",
  },
  {
    id: 7,
    label: "Elevator / lift",
    description: "Vertical lift to move carts between floors.",
    fill: tileColor.fuchsia,
    border: "#f0abfc",
  },
  {
    id: 8,
    label: "Restricted",
    description: "Maintenance only / blocked aisle.",
    fill: "#111827",
    border: "#4b5563",
  },
  {
    id: 9,
    label: "Access corridor",
    description: "Neutral walkway or staging lane.",
    fill: tileColor.slate,
    border: tileColor.slateLight,
  },
  {
    id: 10,
    label: "Sensor cluster",
    description: "Environmental or vibration telemetry island.",
    fill: tileColor.teal,
    border: "#5eead4",
  },
];

const levelOneGrid: FloorGrid = [
  [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
  [9, 0, 9, 5, 5, 5, 9, 6, 6, 9],
  [5, 5, 5, 1, 1, 2, 5, 9, 9, 9],
  [4, 1, 1, 1, 2, 2, 4, 9, 8, 9],
  [4, 3, 3, 2, 2, 2, 4, 9, 8, 9],
  [4, 3, 7, 9, 9, 9, 4, 5, 5, 5],
  [4, 3, 3, 9, 6, 6, 4, 5, 1, 5],
  [9, 9, 9, 9, 9, 9, 9, 5, 5, 5],
  [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
];

const levelTwoGrid: FloorGrid = [
  [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
  [1, 1, 4, 1, 1, 1, 4, 2, 2, 5],
  [1, 1, 4, 1, 1, 1, 4, 2, 2, 5],
  [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
  [2, 2, 4, 1, 1, 1, 4, 1, 1, 5],
  [3, 2, 7, 5, 5, 5, 4, 1, 1, 5],
  [3, 3, 4, 3, 3, 3, 4, 6, 6, 5],
  [5, 5, 5, 5, 5, 5, 5, 9, 9, 9],
  [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
];

const levelThreeGrid: FloorGrid = [
  [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
  [9, 2, 2, 4, 2, 2, 4, 3, 3, 9],
  [9, 2, 2, 4, 2, 2, 4, 3, 3, 9],
  [5, 5, 5, 4, 5, 5, 4, 5, 5, 5],
  [1, 1, 7, 4, 6, 6, 4, 3, 3, 3],
  [1, 1, 4, 4, 4, 4, 4, 3, 3, 3],
  [5, 5, 4, 2, 2, 2, 4, 5, 5, 5],
  [9, 9, 4, 9, 9, 9, 4, 9, 9, 9],
  [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
];

const getSize = (grid: FloorGrid) => ({
  cols: grid[0]?.length ?? 0,
  rows: grid.length,
});

const levelOneAnnotations: FloorAnnotation[] = [
  {
    id: "desk",
    floorId: "L1",
    coord: { x: 1, y: 1 },
    label: "Ops desk",
    kind: "desk",
    detail: "Technician check-in / charging",
  },
  {
    id: "patch-staging",
    floorId: "L1",
    coord: { x: 4, y: 3 },
    label: "Patch staging",
    kind: "task",
    detail: "Fiber + power harness prep",
  },
  {
    id: "inventory-optics",
    floorId: "L1",
    coord: { x: 7, y: 1 },
    label: "QSFP cache",
    kind: "inventory",
    detail: "46x 400G optics",
  },
  {
    id: "inventory-gaskets",
    floorId: "L1",
    coord: { x: 8, y: 1 },
    label: "Gasket bin",
    kind: "inventory",
    detail: "Cold plate kit",
  },
  {
    id: "sensor-l1",
    floorId: "L1",
    coord: { x: 8, y: 6 },
    label: "Leak sensor",
    kind: "sensor",
    status: "idle",
  },
  {
    id: "elevator-l1",
    floorId: "L1",
    coord: { x: 2, y: 5 },
    label: "Lift A",
    kind: "elevator",
  },
];

const levelTwoAnnotations: FloorAnnotation[] = [
  {
    id: "g-02-02",
    floorId: "L2",
    coord: { x: 3, y: 1 },
    label: "g-02-02",
    kind: "server",
    detail: "H100 pod · swap QSFP",
  },
  {
    id: "g-02-03",
    floorId: "L2",
    coord: { x: 4, y: 1 },
    label: "g-02-03",
    kind: "server",
    detail: "load 87%",
  },
  {
    id: "c-01-01",
    floorId: "L2",
    coord: { x: 7, y: 1 },
    label: "c-01-01",
    kind: "server",
    detail: "Mixed NVSwitch pod",
  },
  {
    id: "c-01-02",
    floorId: "L2",
    coord: { x: 8, y: 1 },
    label: "c-01-02",
    kind: "server",
    detail: "Burst spool",
  },
  {
    id: "inventory-l2-cache",
    floorId: "L2",
    coord: { x: 7, y: 6 },
    label: "Fiber cache",
    kind: "inventory",
    detail: "Trunk harness",
  },
  {
    id: "sensor-l2",
    floorId: "L2",
    coord: { x: 8, y: 6 },
    label: "Delta loop",
    kind: "sensor",
    status: "watch",
  },
  {
    id: "elevator-l2",
    floorId: "L2",
    coord: { x: 2, y: 5 },
    label: "Lift A",
    kind: "elevator",
  },
];

const levelThreeAnnotations: FloorAnnotation[] = [
  {
    id: "spine-06",
    floorId: "L3",
    coord: { x: 3, y: 4 },
    label: "Spine 6",
    kind: "server",
    detail: "QSFP replacement",
  },
  {
    id: "cooling-manifold",
    floorId: "L3",
    coord: { x: 5, y: 4 },
    label: "Cooling manifold",
    kind: "task",
    detail: "Delta loop check",
  },
  {
    id: "sensor-l3",
    floorId: "L3",
    coord: { x: 4, y: 6 },
    label: "Vibration sensor",
    kind: "sensor",
    status: "alert",
  },
  {
    id: "elevator-l3",
    floorId: "L3",
    coord: { x: 2, y: 4 },
    label: "Lift A",
    kind: "elevator",
  },
];

export const floorPlanFloors: FabricFloor[] = [
  {
    id: "L1",
    label: "Level 1 · Ops staging",
    level: "L1",
    elevation: "Concourse (0 ft)",
    grid: levelOneGrid,
    annotations: levelOneAnnotations,
    size: getSize(levelOneGrid),
    environmental: {
      temp: "21°C",
      airflow: "Intake plenum",
      humidity: "42%",
    },
  },
  {
    id: "L2",
    label: "Level 2 · GPU fabric",
    level: "L2",
    elevation: "+1 floor",
    grid: levelTwoGrid,
    annotations: levelTwoAnnotations,
    size: getSize(levelTwoGrid),
    environmental: {
      temp: "27°C hot aisle",
      airflow: "Cross-flow managed",
      humidity: "38%",
    },
  },
  {
    id: "L3",
    label: "Level 3 · Network spine",
    level: "L3",
    elevation: "+2 floors",
    grid: levelThreeGrid,
    annotations: levelThreeAnnotations,
    size: getSize(levelThreeGrid),
    environmental: {
      temp: "24°C",
      airflow: "Ceiling return",
      humidity: "36%",
    },
  },
];

export const technicianPathGraph: PathGraph = {
  desk: {
    id: "desk",
    floorId: "L1",
    coord: { x: 1, y: 1 },
    label: "Ops desk",
    type: "start",
    action: "Check-in + briefing",
    priority: "standard",
    distanceMeters: 0,
    links: ["patch-staging", "elevator-l1"],
  },
  "patch-staging": {
    id: "patch-staging",
    floorId: "L1",
    coord: { x: 4, y: 3 },
    label: "Patch staging",
    type: "task",
    action: "Assemble fiber kit",
    priority: "high",
    distanceMeters: 18,
    links: ["desk", "elevator-l1"],
  },
  "elevator-l1": {
    id: "elevator-l1",
    floorId: "L1",
    coord: { x: 2, y: 5 },
    label: "Lift A (L1)",
    type: "elevator",
    action: "Move to GPU floor",
    priority: "standard",
    distanceMeters: 24,
    links: ["desk", "patch-staging", "elevator-l2"],
  },
  "elevator-l2": {
    id: "elevator-l2",
    floorId: "L2",
    coord: { x: 2, y: 5 },
    label: "Lift A (L2)",
    type: "elevator",
    action: "Arrive on GPU floor",
    priority: "standard",
    distanceMeters: 32,
    links: ["elevator-l1", "task-gpu-swap", "task-mix-pod", "l2-cache", "elevator-l3"],
  },
  "task-gpu-swap": {
    id: "task-gpu-swap",
    floorId: "L2",
    coord: { x: 3, y: 1 },
    label: "g-02-02",
    type: "task",
    action: "Swap QSFP + verify optics",
    priority: "critical",
    distanceMeters: 52,
    links: ["elevator-l2", "task-mix-pod"],
  },
  "task-mix-pod": {
    id: "task-mix-pod",
    floorId: "L2",
    coord: { x: 7, y: 1 },
    label: "c-01-01",
    type: "task",
    action: "Reset NVSwitch fabric",
    priority: "high",
    distanceMeters: 68,
    links: ["task-gpu-swap", "l2-cache"],
  },
  "l2-cache": {
    id: "l2-cache",
    floorId: "L2",
    coord: { x: 7, y: 6 },
    label: "Fiber cache",
    type: "inventory",
    action: "Pick spare harness",
    priority: "standard",
    distanceMeters: 82,
    links: ["task-mix-pod", "elevator-l2"],
  },
  "elevator-l3": {
    id: "elevator-l3",
    floorId: "L3",
    coord: { x: 2, y: 4 },
    label: "Lift A (L3)",
    type: "elevator",
    action: "Ride to spine level",
    priority: "standard",
    distanceMeters: 104,
    links: ["elevator-l2", "task-spine-repair", "task-cooling"],
  },
  "task-spine-repair": {
    id: "task-spine-repair",
    floorId: "L3",
    coord: { x: 3, y: 4 },
    label: "Spine 6",
    type: "task",
    action: "Install QSFP + test BER",
    priority: "critical",
    distanceMeters: 116,
    links: ["elevator-l3", "task-cooling"],
  },
  "task-cooling": {
    id: "task-cooling",
    floorId: "L3",
    coord: { x: 5, y: 4 },
    label: "Cooling manifold",
    type: "task",
    action: "Check manifold pressure",
    priority: "high",
    distanceMeters: 126,
    links: ["task-spine-repair", "elevator-l3"],
  },
};

export const routePresets: Record<string, RouteSequence> = {
  baseline: [
    "desk",
    "patch-staging",
    "elevator-l1",
    "elevator-l2",
    "task-gpu-swap",
    "task-mix-pod",
    "l2-cache",
    "elevator-l2",
    "elevator-l3",
    "task-spine-repair",
    "task-cooling",
    "elevator-l3",
    "elevator-l1",
    "desk",
  ],
  priority: [
    "desk",
    "patch-staging",
    "elevator-l1",
    "elevator-l2",
    "task-gpu-swap",
    "elevator-l2",
    "elevator-l3",
    "task-spine-repair",
    "task-cooling",
    "elevator-l3",
    "task-mix-pod",
    "l2-cache",
    "elevator-l2",
    "elevator-l1",
    "desk",
  ],
  distance: [
    "desk",
    "patch-staging",
    "elevator-l1",
    "elevator-l2",
    "task-gpu-swap",
    "task-mix-pod",
    "l2-cache",
    "task-mix-pod",
    "elevator-l2",
    "elevator-l3",
    "task-cooling",
    "task-spine-repair",
    "elevator-l3",
    "elevator-l1",
    "desk",
  ],
};

export const routePresetsOrder = Object.keys(routePresets);
