import {
  FabricFloor,
  FloorAnnotation,
  FloorCluster,
  FloorGrid,
  TileDefinition,
} from "@/lib/floor-plan/types";

const tileColor = {
  slate: "#0f172a",
  slateLight: "#1e293b",
  gray: "#475569",
  emerald: "#22c55e",
  cyan: "#0ea5e9",
  amber: "#fbbf24",
  fuchsia: "#a855f7",
  rose: "#fb7185",
  red: "#b91c1c",
  teal: "#14b8a6",
};

export const tileDefinitions: TileDefinition[] = [
  {
    id: 0,
    label: "Technician desk",
    description: "Start and end point for every field round trip.",
    fill: "#164e63",
    border: "#5eead4",
    textColor: "#ecfeff",
  },
  {
    id: 1,
    label: "GPU pod · in use",
    description: "Fully utilized racks pushing thermal envelope.",
    fill: tileColor.emerald,
    border: "#86efac",
    slurmDiagnostics: {
      allocation: "92% allocated · 410/448 GPUs",
      thermals: "Exhaust 32°C · liquid loop steady",
      notes: "Running H100 queues + active NVLink fabric",
    },
  },
  {
    id: 2,
    label: "Mixed workload",
    description: "Shared CPU/GPU sleds; allocation is fluid.",
    fill: tileColor.cyan,
    border: "#22d3ee",
    slurmDiagnostics: {
      allocation: "61% allocated · 180 GPU eq / 220 CPU cores",
      thermals: "Exhaust 27°C · intake 19°C",
      notes: "Slurm partition MIX-02: preemptible jobs allowed",
    },
  },
  {
    id: 3,
    label: "Idle / standby",
    description: "Capacity available for burst or maintenance.",
    fill: tileColor.gray,
    border: "#cbd5f5",
    slurmDiagnostics: {
      allocation: "5% reserved · 0 active jobs",
      thermals: "Idle 22°C · fans low power",
      notes: "Ready for provisioning or diagnostics",
    },
  },
  {
    id: 4,
    label: "Hot aisle",
    description: "High thermal zone between opposing racks.",
    fill: tileColor.red,
    border: "#fecaca",
  },
  {
    id: 5,
    label: "Cold aisle",
    description: "Conditioned intake path for chilled air.",
    fill: "#0a192f",
    border: "#38bdf8",
  },
  {
    id: 6,
    label: "Inventory cache",
    description: "Spare parts staging, optics, or gaskets.",
    fill: tileColor.amber,
    border: "#fde047",
    textColor: "#0f172a",
  },
  {
    id: 7,
    label: "Elevator / lift",
    description: "Vertical lift to move carts between floors.",
    fill: tileColor.fuchsia,
    border: "#f0abfc",
  },
  {
    id: 8,
    label: "Restricted",
    description: "Maintenance only / blocked aisle.",
    fill: "#111827",
    border: "#4b5563",
  },
  {
    id: 9,
    label: "Access corridor",
    description: "Neutral walkway or staging lane.",
    fill: tileColor.slate,
    border: tileColor.slateLight,
  },
  {
    id: 10,
    label: "Sensor cluster",
    description: "Environmental or vibration telemetry island.",
    fill: tileColor.teal,
    border: "#5eead4",
  },
];

const levelOneGrid: FloorGrid = [
  [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
  [9, 0, 9, 5, 5, 5, 9, 6, 6, 9],
  [5, 5, 5, 1, 1, 2, 5, 9, 9, 9],
  [4, 1, 1, 1, 2, 2, 4, 9, 8, 9],
  [4, 3, 3, 2, 2, 2, 4, 9, 8, 9],
  [4, 3, 7, 9, 9, 9, 4, 5, 5, 5],
  [4, 3, 3, 9, 6, 6, 4, 5, 1, 5],
  [9, 9, 9, 9, 9, 9, 9, 5, 5, 5],
  [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
];

const levelTwoGrid: FloorGrid = [
  [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
  [1, 1, 4, 1, 1, 1, 4, 2, 2, 5],
  [1, 1, 4, 1, 1, 1, 4, 2, 2, 5],
  [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
  [2, 2, 4, 1, 1, 1, 4, 1, 1, 5],
  [3, 2, 7, 5, 5, 5, 4, 1, 1, 5],
  [3, 3, 4, 3, 3, 3, 4, 6, 6, 5],
  [5, 5, 5, 5, 5, 5, 5, 9, 9, 9],
  [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
];

const levelThreeGrid: FloorGrid = [
  [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
  [9, 2, 2, 4, 2, 2, 4, 3, 3, 9],
  [9, 2, 2, 4, 2, 2, 4, 3, 3, 9],
  [5, 5, 5, 4, 5, 5, 4, 5, 5, 5],
  [1, 1, 7, 4, 6, 6, 4, 3, 3, 3],
  [1, 1, 4, 4, 4, 4, 4, 3, 3, 3],
  [5, 5, 4, 2, 2, 2, 4, 5, 5, 5],
  [9, 9, 4, 9, 9, 9, 4, 9, 9, 9],
  [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
];

const getSize = (grid: FloorGrid) => ({
  cols: grid[0]?.length ?? 0,
  rows: grid.length,
});

const levelOneAnnotations: FloorAnnotation[] = [
  {
    id: "desk",
    floorId: "L1",
    coord: { x: 1, y: 1 },
    label: "Ops desk",
    kind: "desk",
    detail: "Technician check-in / charging",
  },
  {
    id: "patch-staging",
    floorId: "L1",
    coord: { x: 4, y: 3 },
    label: "Patch staging",
    kind: "task",
    detail: "Fiber + power harness prep",
  },
  {
    id: "inventory-optics",
    floorId: "L1",
    coord: { x: 7, y: 1 },
    label: "QSFP cache",
    kind: "inventory",
    detail: "46x 400G optics",
  },
  {
    id: "inventory-gaskets",
    floorId: "L1",
    coord: { x: 8, y: 1 },
    label: "Gasket bin",
    kind: "inventory",
    detail: "Cold plate kit",
  },
  {
    id: "sensor-l1",
    floorId: "L1",
    coord: { x: 8, y: 6 },
    label: "Leak sensor",
    kind: "sensor",
    status: "idle",
  },
  {
    id: "elevator-l1",
    floorId: "L1",
    coord: { x: 2, y: 5 },
    label: "Lift A",
    kind: "elevator",
  },
];

const levelOneClusters: FloorCluster[] = [
  {
    id: "desk",
    label: "Ops desk",
    floorId: "L1",
    coord: { x: 1, y: 1 },
    cells: [{ x: 1, y: 1 }],
    kind: "ops",
    summary: "Technician dispatch + briefing",
    tags: ["start"],
  },
  {
    id: "patch-staging",
    label: "Patch staging",
    floorId: "L1",
    coord: { x: 4, y: 3 },
    cells: [
      { x: 4, y: 3 },
      { x: 3, y: 3 },
    ],
    kind: "support",
    summary: "Fiber prep and harness laydown",
    tags: ["fiber", "prep"],
  },
  {
    id: "inventory-optics",
    label: "QSFP cache",
    floorId: "L1",
    coord: { x: 7, y: 1 },
    cells: [{ x: 7, y: 1 }],
    kind: "inventory",
    summary: "400G optics + trunk jumpers",
    inventoryItems: ["qsfp", "fiber-kit"],
  },
  {
    id: "inventory-gaskets",
    label: "Gasket & coolant bin",
    floorId: "L1",
    coord: { x: 8, y: 1 },
    cells: [{ x: 8, y: 1 }],
    kind: "inventory",
    summary: "Cold plate kits, sensors, PSU sleds",
    inventoryItems: ["cooling-kit", "sensor", "psu"],
  },
  {
    id: "toolcrib-l1",
    label: "Tool crib",
    floorId: "L1",
    coord: { x: 7, y: 6 },
    cells: [
      { x: 7, y: 6 },
      { x: 7, y: 5 },
    ],
    kind: "inventory",
    summary: "Install kits, diagnostic packs",
    inventoryItems: ["install-kit", "diagnostic-pack"],
  },
  {
    id: "row7-diagnostics",
    label: "Pod 7 sleds",
    floorId: "L1",
    coord: { x: 2, y: 4 },
    cells: [
      { x: 2, y: 4 },
      { x: 3, y: 4 },
    ],
    kind: "rack",
    summary: "Row 7 sled cluster diagnostics zone",
    tags: ["compute", "row7"],
  },
  {
    id: "plant-chill",
    label: "Chill plant south",
    floorId: "L1",
    coord: { x: 1, y: 6 },
    cells: [
      { x: 1, y: 6 },
      { x: 2, y: 6 },
    ],
    kind: "support",
    summary: "Loop pumps + redundant flow sensors",
    tags: ["cooling"],
  },
  {
    id: "service-bay",
    label: "Service bay",
    floorId: "L1",
    coord: { x: 6, y: 6 },
    cells: [
      { x: 6, y: 6 },
      { x: 6, y: 5 },
    ],
    kind: "service",
    summary: "Robotics + LIDAR maintenance bay",
    tags: ["robotics"],
  },
  {
    id: "elevator-l1",
    label: "Lift A · concourse",
    floorId: "L1",
    coord: { x: 2, y: 5 },
    cells: [
      { x: 2, y: 5 },
      { x: 2, y: 4 },
    ],
    kind: "support",
    summary: "Vertical lift to GPU + spine levels",
    tags: ["elevator"],
  },
];

const levelTwoAnnotations: FloorAnnotation[] = [
  {
    id: "g-02-02",
    floorId: "L2",
    coord: { x: 3, y: 1 },
    label: "g-02-02",
    kind: "server",
    detail: "H100 pod · swap QSFP",
  },
  {
    id: "g-02-03",
    floorId: "L2",
    coord: { x: 4, y: 1 },
    label: "g-02-03",
    kind: "server",
    detail: "load 87%",
  },
  {
    id: "c-01-01",
    floorId: "L2",
    coord: { x: 7, y: 1 },
    label: "c-01-01",
    kind: "server",
    detail: "Mixed NVSwitch pod",
  },
  {
    id: "c-01-02",
    floorId: "L2",
    coord: { x: 8, y: 1 },
    label: "c-01-02",
    kind: "server",
    detail: "Burst spool",
  },
  {
    id: "inventory-l2-cache",
    floorId: "L2",
    coord: { x: 7, y: 6 },
    label: "Fiber cache",
    kind: "inventory",
    detail: "Trunk harness",
  },
  {
    id: "sensor-l2",
    floorId: "L2",
    coord: { x: 8, y: 6 },
    label: "Delta loop",
    kind: "sensor",
    status: "watch",
  },
  {
    id: "elevator-l2",
    floorId: "L2",
    coord: { x: 2, y: 5 },
    label: "Lift A",
    kind: "elevator",
  },
];

const levelTwoClusters: FloorCluster[] = [
  {
    id: "g-02-02",
    label: "g-02-02",
    floorId: "L2",
    coord: { x: 3, y: 1 },
    cells: [
      { x: 3, y: 1 },
      { x: 3, y: 2 },
    ],
    kind: "rack",
    summary: "H100 pod QSFP swap zone",
    tags: ["optics", "qsfp"],
  },
  {
    id: "g-02-03",
    label: "g-02-03",
    floorId: "L2",
    coord: { x: 4, y: 1 },
    cells: [
      { x: 4, y: 1 },
      { x: 4, y: 2 },
    ],
    kind: "rack",
    summary: "GPU sled diagnostics",
  },
  {
    id: "c-01-01",
    label: "c-01-01",
    floorId: "L2",
    coord: { x: 7, y: 1 },
    cells: [
      { x: 7, y: 1 },
      { x: 7, y: 2 },
    ],
    kind: "rack",
    summary: "Mixed NVSwitch pod",
    tags: ["nvlink"],
  },
  {
    id: "c-01-02",
    label: "c-01-02",
    floorId: "L2",
    coord: { x: 8, y: 1 },
    cells: [
      { x: 8, y: 1 },
      { x: 8, y: 2 },
    ],
    kind: "rack",
    summary: "Burst spool + spare capacity",
  },
  {
    id: "bundle-44b",
    label: "Bundle 44B",
    floorId: "L2",
    coord: { x: 4, y: 3 },
    cells: [
      { x: 3, y: 3 },
      { x: 4, y: 3 },
      { x: 5, y: 3 },
    ],
    kind: "rack",
    summary: "Patch panel + labeling work zone",
    tags: ["cabling"],
  },
  {
    id: "delta-loop",
    label: "Delta liquid loop",
    floorId: "L2",
    coord: { x: 4, y: 5 },
    cells: [
      { x: 4, y: 5 },
      { x: 5, y: 5 },
    ],
    kind: "support",
    summary: "Liquid manifold inspection point",
    tags: ["cooling"],
  },
  {
    id: "pod-j",
    label: "Pod J sleds",
    floorId: "L2",
    coord: { x: 8, y: 6 },
    cells: [
      { x: 8, y: 6 },
      { x: 9, y: 6 },
    ],
    kind: "rack",
    summary: "GPU sled bumper install zone",
    tags: ["hardware"],
  },
  {
    id: "inventory-l2-cache",
    label: "Fiber cache",
    floorId: "L2",
    coord: { x: 7, y: 6 },
    cells: [{ x: 7, y: 6 }],
    kind: "inventory",
    summary: "Trunk harness + QSFP staging",
    inventoryItems: ["fiber-kit", "qsfp"],
  },
  {
    id: "elevator-l2",
    label: "Lift A · GPU floor",
    floorId: "L2",
    coord: { x: 2, y: 5 },
    cells: [
      { x: 2, y: 5 },
      { x: 2, y: 4 },
    ],
    kind: "support",
    summary: "Vertical link to concourse + spine",
    tags: ["elevator"],
  },
];

const levelThreeAnnotations: FloorAnnotation[] = [
  {
    id: "spine-06",
    floorId: "L3",
    coord: { x: 3, y: 4 },
    label: "Spine 6",
    kind: "server",
    detail: "QSFP replacement",
  },
  {
    id: "cooling-manifold",
    floorId: "L3",
    coord: { x: 5, y: 4 },
    label: "Cooling manifold",
    kind: "task",
    detail: "Delta loop check",
  },
  {
    id: "sensor-l3",
    floorId: "L3",
    coord: { x: 4, y: 6 },
    label: "Vibration sensor",
    kind: "sensor",
    status: "alert",
  },
  {
    id: "elevator-l3",
    floorId: "L3",
    coord: { x: 2, y: 4 },
    label: "Lift A",
    kind: "elevator",
  },
];

const levelThreeClusters: FloorCluster[] = [
  {
    id: "spine-06",
    label: "Spine 6",
    floorId: "L3",
    coord: { x: 3, y: 4 },
    cells: [
      { x: 3, y: 4 },
      { x: 3, y: 5 },
    ],
    kind: "rack",
    summary: "QSFP uplink sled",
    tags: ["optics"],
  },
  {
    id: "cooling-manifold",
    label: "Cooling manifold",
    floorId: "L3",
    coord: { x: 5, y: 4 },
    cells: [
      { x: 5, y: 4 },
      { x: 5, y: 5 },
    ],
    kind: "support",
    summary: "Loop pressure / delta loop",
    tags: ["cooling"],
  },
  {
    id: "rack-n09",
    label: "Rack N09",
    floorId: "L3",
    coord: { x: 7, y: 3 },
    cells: [
      { x: 7, y: 3 },
      { x: 7, y: 4 },
    ],
    kind: "rack",
    summary: "Smart PDU install site",
    tags: ["power"],
  },
  {
    id: "inventory-l3-toolkit",
    label: "Spine service locker",
    floorId: "L3",
    coord: { x: 5, y: 6 },
    cells: [
      { x: 5, y: 6 },
      { x: 4, y: 6 },
    ],
    kind: "inventory",
    summary: "Harness clamps + spare QSFP",
    inventoryItems: ["qsfp", "install-kit"],
  },
  {
    id: "elevator-l3",
    label: "Lift A · spine",
    floorId: "L3",
    coord: { x: 2, y: 4 },
    cells: [
      { x: 2, y: 4 },
      { x: 2, y: 3 },
    ],
    kind: "support",
    summary: "Return to GPU or concourse",
    tags: ["elevator"],
  },
];

export const floorPlanFloors: FabricFloor[] = [
  {
    id: "L1",
    label: "Level 1 · Ops staging",
    level: "L1",
    elevation: "Concourse (0 ft)",
    grid: levelOneGrid,
    annotations: levelOneAnnotations,
    clusters: levelOneClusters,
    size: getSize(levelOneGrid),
    environmental: {
      temp: "21°C",
      airflow: "Intake plenum",
      humidity: "42%",
    },
  },
  {
    id: "L2",
    label: "Level 2 · GPU fabric",
    level: "L2",
    elevation: "+1 floor",
    grid: levelTwoGrid,
    annotations: levelTwoAnnotations,
    clusters: levelTwoClusters,
    size: getSize(levelTwoGrid),
    environmental: {
      temp: "27°C hot aisle",
      airflow: "Cross-flow managed",
      humidity: "38%",
    },
  },
  {
    id: "L3",
    label: "Level 3 · Network spine",
    level: "L3",
    elevation: "+2 floors",
    grid: levelThreeGrid,
    annotations: levelThreeAnnotations,
    clusters: levelThreeClusters,
    size: getSize(levelThreeGrid),
    environmental: {
      temp: "24°C",
      airflow: "Ceiling return",
      humidity: "36%",
    },
  },
];

export const floorClusterIndex = floorPlanFloors.reduce<Record<string, FloorCluster>>(
  (acc, floor) => {
    floor.clusters?.forEach((cluster) => {
      acc[cluster.id] = cluster;
    });
    return acc;
  },
  {},
);
